import React, { useState } from 'react';
import { 
  X, 
  Bot, 
  Sparkles, 
  Cpu, 
  CheckCircle2, 
  Loader2, 
  BrainCircuit, 
  Zap,
  ArrowRight,
  Database
} from 'lucide-react';
import { BlogPost } from '../types';

interface AiAgentBlogModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSavePost: (newPost: BlogPost) => void;
}

const PRESET_TOPICS = [
  {
    title: 'Building Real-Time Power BI & Azure Synapse Pipelines for Retail',
    category: 'Business Intelligence' as const,
    tags: ['Power BI', 'DirectQuery', 'Azure Synapse', 'ETL'],
  },
  {
    title: 'Deploying Local LLMs with RAG & Vector DBs for Enterprise Legal Contracts',
    category: 'AI & LLMs' as const,
    tags: ['RAG', 'Vector Search', 'LangChain', 'Local LLM'],
  },
  {
    title: 'Automating Multi-Currency Finance Accounts Payable with Python RPA',
    category: 'Process Automation' as const,
    tags: ['Python RPA', 'Automation', 'Finance', 'ERP'],
  },
];

export const AiAgentBlogModal: React.FC<AiAgentBlogModalProps> = ({
  isOpen,
  onClose,
  onSavePost,
}) => {
  const [topic, setTopic] = useState('');
  const [category, setCategory] = useState<'AI & LLMs' | 'Business Intelligence' | 'Process Automation' | 'Data Engineering'>('AI & LLMs');
  const [isGenerating, setIsGenerating] = useState(false);
  const [step, setStep] = useState<number>(0);

  if (!isOpen) return null;

  const handlePresetSelect = (preset: typeof PRESET_TOPICS[0]) => {
    setTopic(preset.title);
    setCategory(preset.category);
  };

  const handleGenerate = () => {
    if (!topic.trim()) {
      alert('Please enter a topic or select a prompt preset.');
      return;
    }

    setIsGenerating(true);
    setStep(1);

    // Step 1: Outlining
    setTimeout(() => {
      setStep(2);
      // Step 2: Synthesis & Code Generation
      setTimeout(() => {
        setStep(3);
        // Step 3: Finalizing & Publishing
        setTimeout(() => {
          const generatedPost: BlogPost = {
            id: `agent-post-${Date.now()}`,
            title: `AI Agent Insights: ${topic.trim()}`,
            slug: topic.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
            excerpt: `Autonomously generated analysis by Algorudix Agentic v3.6 exploring optimal architecture, code snippets, and performance benchmarks for ${topic.trim()}.`,
            content: `
# Executive Overview
*Autonomously generated by Algorudix AI Agent v3.6*

In today's fast-moving enterprise environment, implementation of **${topic.trim()}** requires a decoupled architecture that maximizes processing throughput while minimizing operating costs.

## Technical Architecture & Core Principles

1. **Decoupled Processing Pipeline**: Decouple front-end analytics / UI components from underlying heavy batch jobs.
2. **Context-Aware Guardrails**: Enforce automated validation checks to ensure zero system degradation.
3. **Telemetry & Observability**: Real-time logging of API calls, query execution latency, and error states.

### Code / Strategy Implementation

\`\`\`python
# Algorudix Autonomous Pipeline Generator - ${category}
import async_engine
from algorudix_agent import TelemetryGuard

async def execute_enterprise_pipeline(config):
    guard = TelemetryGuard(target_sla_ms=250)
    async with guard.monitor():
        result = await async_engine.run_workflow(
            topic="${topic.trim()}",
            category="${category}",
            optimize_memory=True
        )
    return result
\`\`\`

## Performance Impact & Key Metrics

- **Sub-500ms Response Times** across large enterprise data models.
- **85%+ Reduction in Manual Processing** via autonomous agentic execution.
- **Seamless Scalability** accommodating multi-region workloads without manual intervention.

---
*Generated by Algorudix AI Intelligence Engine. Evaluated against enterprise benchmark guardrails with 99.6% confidence score.*
            `,
            author: {
              name: 'Algorudix AI Agent',
              role: 'Autonomous Intelligence Engine',
              avatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=250&q=80',
            },
            date: new Date().toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' }),
            readTime: '4 min read',
            category,
            tags: [category.split(' ')[0], 'AI Agent', 'Automation', 'Enterprise'],
            image: category === 'Business Intelligence' 
              ? 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80'
              : 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
            createdType: 'agent',
            agentDetails: {
              model: 'Algorudix Agentic v3.6',
              executionTimeMs: 1680,
              tokensUsed: 2150,
              confidenceScore: '99.6%',
            },
          };

          onSavePost(generatedPost);
          setIsGenerating(false);
          setStep(0);
          setTopic('');
          onClose();
        }, 1200);
      }, 1200);
    }, 1200);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-black/80 backdrop-blur-md animate-in fade-in duration-200 overflow-y-auto">
      <div 
        className="relative w-full max-w-xl bg-slate-900 border border-emerald-500/30 rounded-2xl shadow-2xl overflow-hidden my-8"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-slate-950/90">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-lg bg-emerald-500/10 text-emerald-400 border border-emerald-500/30">
              <Bot className="w-5 h-5 animate-pulse" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white flex items-center gap-2">
                Algorudix AI Agent Writer
                <span className="text-[10px] font-mono text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded">
                  v3.6 Active
                </span>
              </h3>
              <p className="text-xs text-slate-400">Autonomous research, code synthesis & article drafting</p>
            </div>
          </div>
          <button 
            onClick={onClose}
            disabled={isGenerating}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition disabled:opacity-50"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-6">
          
          {/* Preset Prompts */}
          <div>
            <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider block mb-2">
              Instant AI Topic Presets
            </span>
            <div className="space-y-2">
              {PRESET_TOPICS.map((preset, idx) => (
                <button
                  key={idx}
                  type="button"
                  onClick={() => handlePresetSelect(preset)}
                  disabled={isGenerating}
                  className="w-full p-3 rounded-xl bg-slate-950/80 border border-slate-800 hover:border-emerald-500/40 text-left transition group flex items-center justify-between"
                >
                  <div>
                    <p className="text-xs font-semibold text-slate-200 group-hover:text-emerald-300 transition">
                      {preset.title}
                    </p>
                    <div className="flex items-center gap-2 mt-1 text-[10px] text-slate-400">
                      <span className="text-emerald-400">{preset.category}</span>
                      <span>•</span>
                      <span>{preset.tags.join(', ')}</span>
                    </div>
                  </div>
                  <Sparkles className="w-4 h-4 text-slate-600 group-hover:text-emerald-400 transition" />
                </button>
              ))}
            </div>
          </div>

          {/* Custom Topic Input */}
          <div>
            <label className="block text-xs font-semibold text-slate-300 uppercase tracking-wider mb-1">
              Custom Topic or Prompt
            </label>
            <input
              type="text"
              disabled={isGenerating}
              placeholder="e.g. Modernizing Power BI Reports with DAX & Snowflake Aggregations"
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              className="w-full px-3.5 py-2.5 rounded-xl bg-slate-950 border border-slate-800 text-white text-sm focus:outline-none focus:border-emerald-500"
            />
          </div>

          {/* Category Select */}
          <div>
            <label className="block text-xs font-semibold text-slate-300 uppercase tracking-wider mb-1">
              Article Category
            </label>
            <select
              disabled={isGenerating}
              value={category}
              onChange={(e) => setCategory(e.target.value as any)}
              className="w-full px-3.5 py-2.5 rounded-xl bg-slate-950 border border-slate-800 text-white text-sm focus:outline-none focus:border-emerald-500"
            >
              <option value="AI & LLMs">AI & LLMs</option>
              <option value="Business Intelligence">Business Intelligence</option>
              <option value="Process Automation">Process Automation</option>
              <option value="Data Engineering">Data Engineering</option>
            </select>
          </div>

          {/* Live Progress Simulation */}
          {isGenerating && (
            <div className="p-4 rounded-xl bg-slate-950 border border-emerald-500/40 space-y-3 animate-pulse">
              <div className="flex items-center justify-between text-xs font-mono">
                <span className="text-emerald-400 flex items-center gap-2">
                  <Loader2 className="w-3.5 h-3.5 animate-spin" />
                  {step === 1 && 'Step 1/3: Analyzing enterprise topic & vector context...'}
                  {step === 2 && 'Step 2/3: Synthesizing code snippets & architecture diagram...'}
                  {step === 3 && 'Step 3/3: Applying quality audit & guardrails...'}
                </span>
                <span className="text-slate-400">99.6% Confidence</span>
              </div>
              <div className="w-full bg-slate-900 h-2 rounded-full overflow-hidden border border-slate-800">
                <div 
                  className="bg-gradient-to-r from-emerald-500 to-cyan-500 h-full transition-all duration-500"
                  style={{ width: `${(step / 3) * 100}%` }}
                />
              </div>
            </div>
          )}

          {/* Action buttons */}
          <div className="pt-4 border-t border-slate-800 flex items-center justify-between">
            <span className="text-[11px] text-slate-400 flex items-center gap-1">
              <Zap className="w-3.5 h-3.5 text-amber-400" /> Auto-publishes to Blog with AI Agent badge
            </span>
            
            <div className="flex items-center gap-3">
              <button
                type="button"
                onClick={onClose}
                disabled={isGenerating}
                className="px-4 py-2 rounded-xl text-xs font-semibold text-slate-400 hover:text-white transition disabled:opacity-50"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={handleGenerate}
                disabled={isGenerating}
                className="px-5 py-2.5 rounded-xl bg-gradient-to-r from-emerald-500 via-teal-600 to-cyan-600 hover:from-emerald-400 hover:to-cyan-500 text-white text-xs font-semibold shadow-lg shadow-emerald-950 transition flex items-center gap-2 cursor-pointer disabled:opacity-50"
              >
                {isGenerating ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    <span>Agent Generating...</span>
                  </>
                ) : (
                  <>
                    <Bot className="w-4 h-4" />
                    <span>Generate AI Article</span>
                  </>
                )}
              </button>
            </div>
          </div>

        </div>

      </div>
    </div>
  );
};
